### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by SeZuo** [dandels/dmodman#20]
Tried to download a lot of things and crashed dmodman.

Now this error comes on launch.

```bash
thread 'main' panicked at src/cache/file_index.rs:60:103:
called `Option::unwrap()` on a `None` value
```

I deleted the bad entries from the cache list to be able to launch the app again.

**Comment by SeZuo** [comment]
https://www.nexusmods.com/witcher3/mods/6621?tab=files&file_id=55648&nmm=1

This is the mod that seems to crash the app reliably with error
```bash
thread 'tokio-runtime-worker' panicked at src/cache/file_index.rs:90:71:
called `Option::unwrap()` on a `None` value
```

**Comment by dandels** [comment]
This should be fixed as part of the backend rewrite I did for [0.3.0-beta](https://github.com/dandels/dmodman/releases/tag/v0.3.0-beta). I uploaded a pre-release that you can try.
